import assert from 'node:assert/strict';
import {Game,CLASSES,CLASS_WEAPONS,LEGENDS,itemForSlot,seeded,validateSave,playerSkill} from '../dist/sim.mjs';
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
function setup(cls){const g=new Game(undefined,721);g.begin([cls]);g.enemies=[];const p=g.players[0];p.profile.ranks=[4,4,4,0,0,0];return{g,p};}
function gear(g,p,keys){keys.forEach((key,n)=>p.profile.equipped[['ring','relic','armor','weapon'][n]]=itemForSlot(['ring','relic','armor','weapon'][n],p.cls,3,4,seeded(n+8),key));g.profileRefresh(p);p.stats.crit=0;}
function cast(g,p,slot=0){p.cd=[0,0,0];p.mana=100;assert(g.skill(p,slot,{aim:{x:p.x+2,z:p.z}}));}
let casts=0;
for(const cls of Object.keys(CLASSES))for(let source=0;source<5;source++)for(let rune=0;rune<3;rune++){
 const {g,p}=setup(cls);if(source!==0){const choices=[source,...[0,1,2,3,4].filter(n=>n!==source).slice(0,2)];p.profile.skillChoices=choices;}assert(g.chooseRune(0,0,rune));p.x=-26;p.z=-14;const e=g.spawnEnemy('brute',p.x+2,p.z,1);e.hp=e.maxHp=100000;e.cd=100;cast(g,p);for(let n=0;n<35;n++)g.step(.04,[{}]);assert(Number.isFinite(p.hp));assert(validateSave(JSON.parse(JSON.stringify(g.save))),cls+' save');casts++;
}
assert.equal(casts,120);
// Two separate drop checks on the same ordinary monster; success does not depend on the killer.
const coop=new Game(undefined,73);coop.begin(['knight','druid']);coop.enemies=[];
const outcomes=new Set();for(let n=0;n<250;n++){const before=coop.drops.length,e=coop.spawnEnemy('brute',-26,-14,1);coop.kill(e,coop.players[0]);outcomes.add(coop.drops.slice(before).reduce((a,d)=>a|(1<<d.owner),0));}assert.equal(outcomes.size,4,'Neither, either player alone, and both must be possible');
const counts=coop.players.map(p=>coop.drops.filter(d=>d.owner===p.id).length);assert(counts.every(n=>n>40&&n<110));assert(coop.drops.every(d=>d.item.cls===coop.players[d.owner].cls));
const elite=coop.spawnEnemy('elite',-26,-14,1),before=coop.drops.length;coop.kill(elite,coop.players[0]);assert.equal(coop.drops.length-before,2);
const twins=new Game(undefined,18);twins.begin(['necromancer','necromancer']);twins.enemies=[];twins.kill(twins.spawnEnemy('elite',-26,-14,1),twins.players[0]);assert.deepEqual(twins.drops.map(d=>d.owner),[0,1]);assert.notEqual(twins.drops[0].item.id,twins.drops[1].item.id);
for(const cls of Object.keys(CLASSES))for(let i=0;i<30;i++)assert.equal(itemForSlot('weapon',cls,5,2,seeded(i)).weaponType,CLASS_WEAPONS[cls][0]);
const {g,p}=setup('necromancer');gear(g,p,['legion','eternal','ossuary']);p.x=-26;p.z=-14;p.chargeResource=6;g.chooseRune(0,0,2);cast(g,p);assert.equal(g.summons.filter(m=>m.type==='wraith').length,7);assert.equal(g.summons.filter(m=>m.type==='archer').length,2);assert.equal(g.summons.filter(m=>m.type==='golem').length,1);assert(g.summons.every(m=>m.life===Infinity));cast(g,p);assert.equal(g.summons.length,10,'Repeated summoning respects caps');for(let n=0;n<600;n++)g.step(.04,[{}]);assert.equal(g.summons.length,10);p.profile.equipped.relic=null;g.profileRefresh(p);assert(g.summons.every(m=>m.life===12));
const combinations={knight:['cyclone','aftershock'],mage:['shatter','starfire'],ranger:['seeker','hail'],assassin:['shadow','twinshade'],engineer:['overdrive','battery'],druid:['wildheart','wildstorm'],monk:['thunder','stillstorm']};
for(const [cls,keys]of Object.entries(combinations)){const {g,p}=setup(cls);gear(g,p,keys);p.x=-26;p.z=-14;for(let slot=0;slot<3;slot++)cast(g,p,slot);assert(g.zones.length||g.summons.length);if(cls==='knight')assert.equal(g.zones.filter(z=>z.burst).length,3);if(cls==='mage')assert(g.zones.some(z=>z.starfire));if(cls==='ranger')assert.equal(g.zones.find(z=>z.type==='rain').life,7);if(cls==='assassin')assert.equal(g.zones.filter(z=>z.type==='blades').length,2);if(cls==='engineer')assert.equal(g.summons.length,2);if(cls==='druid')assert(g.zones.find(z=>z.type==='roots').follow);if(cls==='monk')assert(g.zones.some(z=>z.follow));}
const load=setup('mage');assert(load.g.chooseSkill(0,0,3));assert(!load.g.chooseSkill(0,1,3));load.p.cd[0]=7;load.g.saveLoadout(0,0);assert(load.g.chooseSkill(0,0,4));assert.equal(load.p.cd[0],7);load.g.applyLoadout(0,0);assert.equal(playerSkill(load.p,0).sourceIndex,3);load.p.x=-26;load.p.z=-14;assert(!load.g.chooseSkill(0,0,4));assert(validateSave(JSON.parse(JSON.stringify(load.g.save))));
for(let n=0;n<72;n++)load.p.profile.bag.push(itemForSlot('ring','mage',1,0,seeded(n)));const reward=itemForSlot('ring','mage',5,4,seeded(99),'starfire');load.g.giveItem(load.p,reward);assert.equal(load.p.profile.overflow[0].id,reward.id);const restored=validateSave(JSON.parse(JSON.stringify(load.g.save)));assert.equal(restored.profiles['0:mage'].overflow[0].id,reward.id);load.p.profile.bag.pop();load.g.claimOverflow(0);assert(load.p.profile.bag.some(i=>i.id===reward.id));
console.log(JSON.stringify({skillAndRuneCasts:casts,independentDropCounts:counts,checks:['personal loot and dedicated weapons','ten permanent mixed summons and caps','all eight class build effects','town skill selection and saved presets','overflow reward persistence']}));
