import assert from'node:assert/strict';
import{Game,CLASSES,ROOMS,LEGENDS,stats,itemForSlot,freshSave,validateSave,seeded}from'../dist/sim.mjs';
function start(g,classes){g.begin(classes);g.players.forEach((p,i)=>{p.x=ROOMS[1].x+i*1.5;p.z=ROOMS[1].z;});g.room=1;}
const results=[];
function check(name,fn){fn();results.push(name);}
check('Equipment swapping derives stats without cumulative inflation',()=>{const g=new Game();start(g,['knight']);const p=g.players[0],base=stats(p.profile).damage;const old=p.profile.equipped.weapon,newItem=itemForSlot('weapon','knight',7,4,seeded(13),'echo');p.profile.bag.push(newItem);for(let i=0;i<20;i++){assert(g.equip(0,newItem.id));assert(p.stats.damage>base);assert(g.equip(0,old.id));assert.equal(p.stats.damage,base);}assert.equal(p.profile.bag.length,1);});
check('Every legendary effect has a material combat consequence',()=>{for(const legend of Object.keys(LEGENDS)){const g=new Game(undefined,33);start(g,['knight']);const p=g.players[0];p.profile.equipped.ring=itemForSlot('ring','knight',1,4,seeded(2),legend);g.profileRefresh(p);assert(p.stats.legends.includes(legend));p.hp=p.stats.hp/2;p.stats.crit=75;const a=g.enemies[0],b=g.enemies[1];a.x=p.x+1;a.z=p.z;b.x=p.x+1.5;b.z=p.z;const hp=b.hp;if(legend==='frost'){p.invuln=0;g.hurt(p,1,null);assert(a.frozen>0);}else if(legend==='blood'){const before=p.hp;g.hitEnemy(a,12,p);assert(p.hp>before);}else if(legend==='echo'){g.hitEnemy(a,12,p,'basic');assert(b.hp<hp);}else if(legend==='nova'){g.skill(p,2,{});assert(g.fx.some(f=>f.color==='#bdadff'));}else if(legend==='vortex'){g.skill(p,0,{});assert(g.fx.find(f=>f.type==='spin').r>4.5);}else if(legend==='chain'){for(let i=0;i<4;i++){a.hp=a.maxHp;a.dead=false;g.hitEnemy(a,1,p);}assert(g.fx.some(f=>f.type==='lightning'));}}});
check('Skills spend resource and respect cooldown, pause freezes gameplay',()=>{const g=new Game();start(g,['mage']);const p=g.players[0];assert(g.skill(p,0,{}));const mana=p.mana;assert(!g.skill(p,0,{}));assert.equal(p.mana,mana);const time=g.time,cd=p.cd[0];g.paused=true;for(let i=0;i<100;i++)g.step(.04,[{attack:true,skills:[true,true,true]}]);assert.equal(g.time,time);assert.equal(p.cd[0],cd);assert.equal(p.mana,mana);});
check('Co-op keeps independent gear, shared rewards and three-second revival',()=>{const g=new Game();start(g,['knight','mage']);const [a,b]=g.players;g.chests.push({x:0,z:0,open:false});g.openChest(g.chests[0]);assert.equal(a.profile.bag.length,1);assert.equal(b.profile.bag.length,1);assert.equal(a.profile.bag[0].cls,'knight');assert.equal(b.profile.bag[0].cls,'mage');assert.notEqual(a.profile.bag[0].id,b.profile.bag[0].id);g.enemies=[];g.spawnEnemy('wisp',19,-19,0);b.down=true;b.hp=0;a.x=b.x;a.z=b.z;for(let i=0;i<50;i++)g.step(.04,[{},{}]);assert.equal(b.down,true);for(let i=0;i<30;i++)g.step(.04,[{},{}]);assert.equal(b.down,false);assert(b.hp>0);});
check('Skill respec returns all spent points; negative gold is impossible',()=>{const g=new Game();start(g,['ranger']);const p=g.players[0];assert(g.learn(0,4));assert(g.learn(0,0));assert(!g.learn(0,2));g.respec(0);assert.equal(p.profile.points,2);assert.deepEqual(p.profile.ranks,[1,1,1,0,0,0]);assert.equal(g.upgrade(0,p.profile.equipped.weapon.id),false);assert.equal(g.save.gold,0);});
check('Save round-trip preserves both profiles, mute volume and rejects corruption',()=>{const g=new Game();start(g,['knight','mage']);g.save.settings.volume=0;const item=itemForSlot('relic','mage',6,4,seeded(8));g.players[1].profile.bag.push(item);const raw=JSON.stringify(g.save),round=validateSave(JSON.parse(raw));assert(round);assert.equal(round.settings.volume,0);assert.equal(round.profiles['1:mage'].bag[0].id,item.id);const corrupt=JSON.parse(raw);corrupt.gold=-1;assert.equal(validateSave(corrupt),null);const broken=JSON.parse(raw);broken.profiles['0:knight'].equipped.weapon.affixes=[{key:'__proto__',value:5}];assert.equal(validateSave(broken),null);});
check('Boss reward, depth unlock, run restart and death preserve progress',()=>{const g=new Game(undefined,55);start(g,['knight','mage']);g.enemies=[];const boss=g.spawnEnemy('boss',0,0,4);g.kill(boss,g.players[0]);assert.equal(g.completed,true);assert.equal(g.save.bestDepth,2);for(const p of g.players)assert(p.profile.bag.some(i=>i.rarity===4));const level=g.players[0].profile.level;assert(g.nextDepth());assert.equal(g.depth,2);assert.equal(g.completed,false);assert.equal(g.players[0].profile.level,level);assert(g.players[0].profile.bag.some(i=>i.rarity===4));for(const p of g.players){p.x=ROOMS[1].x;p.z=ROOMS[1].z;p.invuln=0;g.hurt(p,100000,null);}assert.equal(g.state,'defeat');assert(validateSave(JSON.parse(JSON.stringify(g.save))));});
check('Open field permits travel between regions without encounter gates',()=>{const g=new Game();g.begin(['knight']);assert(g.allowed(20,0));assert(g.walkable(20,0));assert(g.walkable(-20,0));assert(!g.walkable(100,0));});
console.log(JSON.stringify({passed:results.length,checks:results},null,2));
